export default {
    list: {
        user: 'list-user',
        tenant: 'list-tenant',
        post: 'list-post',
        product: 'list-product',
        request: 'list-request',
        audit: 'list-audit',
        building: 'list-building',
        address: 'list-address',
        unit: 'list-unit',
        propertyManager: 'list-property_manager',
        district: 'list-district',
        template: 'list-template',
        provider: 'list-provider',
        requestCategory: 'list-service_request_category',
    },
    view: {
        user: 'view-user',
        userSetting: 'view-user_setting',
        tenant: 'view-tenant',
        post: 'view-post',
        product: 'view-product',
        provider: 'view-provider',
        building: 'view-building',
        address: 'view-address',
        unit: 'view-unit',
        propertyManager: 'view-property_manager',
        district: 'view-district',
        realEstate: 'view-real_estate',
        template: 'view-template',
        requestCategory: 'view-service_request_category'
    },
    create: {
        comment: 'post-comment',
        post: 'post-post',
        user: 'post-user',
        tenant: 'post-tenant',
        postToAnyLocation: 'post-located-post',
        product: 'post-product',
        provider: 'post-provider',
        tenantRequest: 'post-request_tenant',
        serviceRequest: 'post-request_service',
        request: 'post-request',
        building: 'post-building',
        address: 'post-address',
        unit: 'post-unit',
        propertyManager: 'post-property_manager',
        district: 'post-district',
        template: 'post-template',
        requestCategory: 'post-service_request_category'
    },
    update: {
        requestTenant: 'edit-request_tenant',
        user: 'edit-user',
        userSettings: 'edit-user_setting',
        tenant: 'edit-tenant',
        comment: 'edit-comment',
        post: 'edit-post',
        product: 'edit-product',
        provider: 'edit-provider',
        request: 'edit-request',
        tenantRequest: 'edit-request_tenant',
        serviceRequest: 'edit-request_service',
        building: 'edit-building',
        address: 'edit-address',
        unit: 'edit-unit',
        propertyManager: 'edit-property_manager',
        district: 'edit-district',
        realEstate: 'edit-real_estate',
        template: 'edit-template',
        requestCategory: 'edit-service_request_category'
    },
    delete: {
        user: 'delete-user',
        tenant: 'delete-tenant',
        post: 'delete-post',
        product: 'delete-product',
        provider: 'delete-provider',
        request: 'delete-request',
        building: 'delete-building',
        address: 'delete-address',
        unit: 'delete-unit',
        propertyManager: 'delete-property_manager',
        district: 'delete-district',
        template: 'delete-template',
        requestCategory: 'delete-service_request_category'
    },
    publish: {
        post: 'publish-post',
        product: 'publish-product'
    },
    pin: {
        post: 'pin-post'
    },
    assign: {
        provider: 'assign-provider',
        request: 'assign-request',
        manager: 'assign-property_manager',
    }
};
